[versions]
agp = "8.12.3"
datastorePreferences = "1.1.7"
glanceAppwidget = "1.1.1"
glanceMaterial3 = "1.1.1"
hiltWork = "1.3.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
kspVersion = "2.2.20-2.0.3"
hilt-nav = "1.3.0"
hiltVersion = "2.57.2"
ktor = "3.3.2"
kotlinxSerializationJson = "1.9.0"
nav_version = "2.9.6"
protobufKotlinLite = "4.33.1"
qiblacompass = "1.0.0"
serialize-kotlin = '2.2.21'
room = "2.8.3"
materialIconsExtended = "1.7.8"
playServicesLocation = "21.3.0"
workRuntimeKtx = "2.11.0"

[libraries]
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }


#dataStore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }

#hilt
android-hilt = {group="com.google.dagger",name="hilt-android",version.ref="hiltVersion"}
android-hilt-test ={group="com.google.dagger",name="hilt-android-testing",version.ref="hiltVersion"}
hilt-comiler = {group="com.google.dagger",name="hilt-compiler",version.ref="hiltVersion"}
hilt-nav = {group="androidx.hilt",name="hilt-navigation-compose",version.ref="hilt-nav"}
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }


#galance
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glanceMaterial3" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }

#navigation
compose-navigation ={group="androidx.navigation",name="navigation-compose",version.ref="nav_version"}

#ktor
ktor-client-core = { group = "io.ktor",name="ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor",name="ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor",name="ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor",name="ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-loggin = {group="io.ktor",name = "ktor-client-logging-jvm",version.ref="ktor"}
ktor-auth ={group="io.ktor",name="ktor-client-auth",version.ref="ktor"}
ktor-cio = {group="io.ktor",name="ktor-client-cio",version.ref = "ktor"}

#serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx",name="kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }


#location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }


#room
qiblacompass = { module = "io.github.hassaanjamil:qiblaCompass", version.ref = "qiblacompass" }
room-runtime = { group = "androidx.room",name="room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room",name="room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room",name="room-ktx", version.ref = "room" }
room-guava = { group = "androidx.room",name="room-guava", version.ref = "room" }
room-testing = { group = "androidx.room",name="room-testing", version.ref = "room" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-serialize-plugin={id="org.jetbrains.kotlin.plugin.serialization", version.ref ="serialize-kotlin"}

#hilt
hilt-andorid = {id="com.google.dagger.hilt.android",version.ref = "hiltVersion"}


# KSP plugin
ksp-android = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }

